version: '3'

services:
  web:
    image: ivankhoda/diary:prod
    ports:
      - "3000:3000"
    env_file:
      - .env/production/database
      - .env/production/web
      - .env/production/telegram
    networks:
      - diary

  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - diary

  database:
    image: postgres:16-alpine
    env_file:
      - .env/production/database
      - .env/production/web
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - diary

  db-creator:
      image: ivankhoda/diary:prod
      command: [ "bin/rails", "db:create" ]
      env_file:
        - .env/production/database
        - .env/production/web
      deploy:
        restart_policy:
          condition: none
      networks:
        - diary

  db-migrator:
      image: ivankhoda/diary:prod
      command: [ "bin/rails", "db:migrate" ]
      env_file:
        - .env/production/database
        - .env/production/web
      deploy:
        restart_policy:
          condition: none
      depends_on:
        - db-creator
      networks:
        - diary

volumes:
  db_data:

#Docker Networks
networks:
  diary:
    driver: overlay
    attachable: true
