version: '3'

services:
  web:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/database
      - .env/development/web
    networks:
      - menu
  nginx:
    build: .
    image: nginx:alpine
    ports:
      - "81:80"
      - "82:81"
    volumes:
        - ./docker/nginx/menu.conf:/etc/nginx/conf.d/menu.conf
    networks:
      - menu
  redis:
    image: redis

  database:
    image: postgres
    env_file:
      - .env/development/database
      - .env/development/web
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
  gem_cache:

networks:
  menu:
    driver: overlay
    attachable: true