# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('DATABASE_HOST') || "127.0.0.1" %>
  username: <%= ENV.fetch('POSTGRES_USER') || postgres %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') || postgres %>
  database: <%= ENV.fetch('POSTGRES_DB') || menu_development %>
  pool: 5
  variables:
    statement_timeout: 5000

development:
  <<: *default
test:
  <<: *default
  database: menu_test

production:
  <<: *default
